# Generated by Django 5.1.7 on 2025-04-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sawaed_app', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handymanprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='handymanprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='handymanprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.jpeg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'عميل'), ('handyman', 'عامل يدوي')], default='client', max_length=50),
        ),
        migrations.AlterField(
            model_name='handymanprofile',
            name='availability',
            field=models.BooleanField(null=True),
        ),
    ]
