# Generated by Django 5.1.6 on 2025-04-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sawaed_app', '0011_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='verb',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
